[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "cf57ebeee2d6352f8acccf12f5c248637baf066b"
os = "macos"

    [[libmseed.download]]
    sha256 = "7838c722efd8319c5b51c573d44abba37004ec413a2a3f4843e9dd80f5b14320"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.aarch64-apple-darwin.tar.gz"
[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "bd3920704c7a8e587b9449372318cefa5fe5212d"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "784028e3df9e816e47126c98384b9a36194fe4837a06f153b227ee49cbb35746"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.aarch64-linux-gnu.tar.gz"
[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "bde94152bfce7f410d8378d8e026841483f0735c"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "7878d27cb0724e9c3c160c97985e3d6182b76ecdf11de0c8fc861269466f4d3f"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.aarch64-linux-musl.tar.gz"
[[libmseed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b72f6a2d86901ea273ecd2f1129ab539d7bb75dd"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "7b60dfa6ae7a79d0a6f3f797ed1ba581cc4f27379efe41cb3570ad7ee6599086"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.armv6l-linux-gnueabihf.tar.gz"
[[libmseed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "816bb0ec4a2b5926ee0d36bbb66c821f48986cc8"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "01a842ae85a56f4bed2d40fe079797cc8ecbc05da306ee4ffc56f7eeebee93bf"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.armv6l-linux-musleabihf.tar.gz"
[[libmseed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b8eb1af73b92335850b1c4a9e365e988fe1de2e3"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "bfb8e7d432b2efe8234e37202f31ed28ca74db72da8a76ab3eae61e333a01b48"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.armv7l-linux-gnueabihf.tar.gz"
[[libmseed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e911916ed2b5b08caf5128940892aa0fc503d225"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "8ccb07a5303b815ab546f58fd40eb6a630db78e44b104673946d40cab5367542"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.armv7l-linux-musleabihf.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "c2177eb612cfddf317a216eb2c9d574494754f22"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "2d36cb23fd4130759b0f7f0da8377ddb624c9a38addb2aac0fe8028cc76753d3"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.i686-linux-gnu.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "9170a0cf6a8b4ff6fddaa2b66607886870ed3055"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "ce214d3087d5d3e84eef9b7948d4d7a4216521db350e362e6ed991347b0da15b"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.i686-linux-musl.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "43fb7cedaed668cbb8911a378a9dab92de102d3c"
os = "windows"

    [[libmseed.download]]
    sha256 = "8237aed902f6b8ae92e9cd18b7191020731e9f3cb2280c5bc4ae9a564b755df8"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.i686-w64-mingw32.tar.gz"
[[libmseed]]
arch = "powerpc64le"
git-tree-sha1 = "d45705a6a056748ed79cadbc4ef352691d87f45e"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "d002d51dbbe80c5f2ff1676c44410c7fc158e678ee78c2c2f8f6e880a278dec1"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.powerpc64le-linux-gnu.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "c33521a852a0c2ead1a77cf682516fc441e11179"
os = "macos"

    [[libmseed.download]]
    sha256 = "f76a8d37a24d2207473215fcfc6f012fe352b9aecdf3a82808705a7498fac2fa"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.x86_64-apple-darwin.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "14a024f3da5b01d4ac13cc540b74d65f6282cb63"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "482bb4d5191bb1303bb500fd3062fa07c9a8287ef4ee3a3668a0b8aa9400ebda"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.x86_64-linux-gnu.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "3047a01b6346e3aa4b190f0b3462e63ba599cd95"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "1c87dcdb08395a0adfce1b2ce5379a8d0e528af186ad586b0a17236b44fe0e45"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.x86_64-linux-musl.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "753451b805e87513811b965974c2f69e6a8ca867"
os = "freebsd"

    [[libmseed.download]]
    sha256 = "7ca9fe585866665ba91d25e86351ed0d4ba0f88a2c762d6569d03007d03df7cb"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.x86_64-unknown-freebsd.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "35fe3fc4026c4c046fc043369d90f2a978bc56fe"
os = "windows"

    [[libmseed.download]]
    sha256 = "a407e7c0e01dcf8425f4026a1f506983b0df3fc01fa38318324a7bd0dec1766e"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.18+0/libmseed.v3.0.18.x86_64-w64-mingw32.tar.gz"
