[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "b71e415a9bce8cc082d22bf914cca67acf0f0b5c"
os = "macos"

    [[libmseed.download]]
    sha256 = "13a37f8f862f3ac59b82292e232a7addccea65636eaf4034dc658798d1434ec4"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.aarch64-apple-darwin.tar.gz"
[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "dea3a2ccbc22568ed03b6d3d62c69277f65599f3"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "6cc6baaef7c8f477c6c1705513ff5774b2e1d97e5782cc0c71e239c0b78e8013"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.aarch64-linux-gnu.tar.gz"
[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "0ff467481edf83cbfcba9b133c231f5a93999ae8"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "3758b6f373d3828dbe98e4fdb129bdf94491a2c63d1e64cf1911e35ade1e241b"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.aarch64-linux-musl.tar.gz"
[[libmseed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a67fcd6c77229edf040428d3d496367fe402a5f4"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "a7fe3ba95e7d822f980bdddb31b8099389236b48e184f432558add8b971652fc"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.armv6l-linux-gnueabihf.tar.gz"
[[libmseed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c1cc7e8ac62972fd139076e7bc142243fb33a02f"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "2ab1ad88919d7b47ed611b95ff2a1e14e51f5cb35cab0e2b2f4a8850a544ff65"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.armv6l-linux-musleabihf.tar.gz"
[[libmseed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f33cd272079056b342918fb656f2a7b83bab19f1"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "fdbd956e35d47fb9cb4cacbe9f37b517e13ea940390ed371f7a611d976aacc1a"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.armv7l-linux-gnueabihf.tar.gz"
[[libmseed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5e2ab48b12596ce2159037675d499e330719c36c"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "bc0038ca4bc38bbc7144ffac8ba832db779a589a707de7bd3cec0ecc20ee99a6"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.armv7l-linux-musleabihf.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "3cf74afb034bbeacd00bb4e678d3ca9349f1d32b"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "93a3e5a5d3409f76905f2117c0031b7d79ec6e4b267538e7d8b75152489bc844"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.i686-linux-gnu.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "5d6df598d4d0f6760f9636b9192811df41d96331"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "03d2207e483440d2217183820a6208288a831cd67508ff7ebf29677e7b557c8c"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.i686-linux-musl.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "3d9eaf12fa403574f0b3f695d6ccaee166437eb7"
os = "windows"

    [[libmseed.download]]
    sha256 = "f750a8ccf9e65ccde1abb11beb9025e1c7911bd7201e46af0ea80bba0ff4ebc5"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.i686-w64-mingw32.tar.gz"
[[libmseed]]
arch = "powerpc64le"
git-tree-sha1 = "b9273ad970c1eddb56878f6644efcc1570fa65ac"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "d431057244ca0f50b65b2ed4b4d14c64c59b89e0a8f48224348fbc5c5bc22a68"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.powerpc64le-linux-gnu.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "5b56cb4947fef2f22462f32019e75e84e271f68a"
os = "macos"

    [[libmseed.download]]
    sha256 = "a6157493a7de6f6449285c721e582a93ff0c1d2c84a0a93ac0cee6196c3250ae"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.x86_64-apple-darwin.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "e5d03b73476fc1c2010d52ada4ebcc67391d65e6"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "1473e16d242ce298a1308b80c4612cd26382c3af78f94bc0b4df2888cf9cb42b"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.x86_64-linux-gnu.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "85ff58b21656f50cbd5302e2b0026c362296393d"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "72bb69ddf67a27b9524ec4a710ba5545be5a0890756eb980172d86ed423c144d"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.x86_64-linux-musl.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "0cc771f645c677ff0a50b72c247be646087d042e"
os = "freebsd"

    [[libmseed.download]]
    sha256 = "93f97097069047e1520eda66dc56d46636263632d89420d0f01e2485b001bd15"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.x86_64-unknown-freebsd.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "4f35c575fa349d1415e67da90539bc98608002c1"
os = "windows"

    [[libmseed.download]]
    sha256 = "10873b2407219cbad374b4d6f8878d4bcd5ac2a4413a6d6c189538547183be41"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.16+0/libmseed.v3.0.16.x86_64-w64-mingw32.tar.gz"
