[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "1709773d3f15c421b56db18139d65ecd4d5ba658"
os = "macos"

    [[libmseed.download]]
    sha256 = "7e63b79aefdaed446069361ca5cf2a2d03ad09787729c4eb7b8173af9ece0091"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.aarch64-apple-darwin.tar.gz"
[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "f6f914d731506e83dc59ebc651a5d158eeaf7506"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "7257b253bf47a0095afc29b5fc8fb4014c3e5fdb678af88ba0440ef25d6fe352"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.aarch64-linux-gnu.tar.gz"
[[libmseed]]
arch = "aarch64"
git-tree-sha1 = "80e1410227f985adcc94073aae26483a8da35286"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "9ada8d1f912f11a6f6d0309867edbc43df988de08e77a66474d038806220a235"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.aarch64-linux-musl.tar.gz"
[[libmseed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "706abe6403500158928bf118213a571496076115"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "3f0c4b3b65b0084f48f04a6c839af3ffa1601fd42dbab6dbe2032c2fdc53e631"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.armv6l-linux-gnueabihf.tar.gz"
[[libmseed]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2ace22a3231b539549ef52979e41404fe7940bed"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "a3fd4a269fe085696f18e55b7de9facfbf901edabbf8bd09c7bbe1fa782520fc"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.armv6l-linux-musleabihf.tar.gz"
[[libmseed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "51fa66ede2153123b8a15433e6b48b1ba35d2c14"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "a836bd7dec1f14bd1b8ca3eb18d71f7c982f4d23b9c8b5daf7af4cab033fbe5f"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.armv7l-linux-gnueabihf.tar.gz"
[[libmseed]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "be422df46008631f28700667e54b26a0534b1df8"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "fc5e5adfe4b45d0e5d7ea7e6357e86fd74c301c23a9cdfab15344d4a1444c39f"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.armv7l-linux-musleabihf.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "a2f5a6df91fe8da5fa5f7bab7273131d8926940b"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "c0a2947c8c472813cc45782bae0c3e83cb45cfe9ccb4fcbc61ca5f13df9efe4c"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.i686-linux-gnu.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "3ccec73eb41f974705867e00c896693b6e00484b"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "4b86ed2e7745c930d878321684a4396e009025fa0cad2ff62317ad4fbfefb2aa"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.i686-linux-musl.tar.gz"
[[libmseed]]
arch = "i686"
git-tree-sha1 = "835258a821c52f0f5e11b348df4101657536e4c3"
os = "windows"

    [[libmseed.download]]
    sha256 = "bc0df394067ffd3218d95fe8dc8656aa698d4a9556882ef466a109c6a60993b4"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.i686-w64-mingw32.tar.gz"
[[libmseed]]
arch = "powerpc64le"
git-tree-sha1 = "b10b66196076a46120ba1568fc789f43cbeb517f"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "8579f66cd9469bf8b30915741e643ec9baf93f5cbbf61cf24f212acb8a876386"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.powerpc64le-linux-gnu.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "8b34fa3c4e84b8690879eb3d18fe0d60917db3b1"
os = "macos"

    [[libmseed.download]]
    sha256 = "7c17c6c0c9a891a88e7b5f079801492f214c266f8dae042be3fb17dbe15d36e7"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.x86_64-apple-darwin.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "78d5a22aa3c056c639811eb5068cbabd76afac81"
libc = "glibc"
os = "linux"

    [[libmseed.download]]
    sha256 = "c186db9ec7fada052fde2258146c9410c3608bc751009c5b3b0f60c3cb9f7006"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.x86_64-linux-gnu.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "e0a91189c0c036aef95710cd1e96a0d2b28e1900"
libc = "musl"
os = "linux"

    [[libmseed.download]]
    sha256 = "31d9c856d67e89b0459e45686f61b8c637f75a20eea1273277c70c21ba2e85c5"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.x86_64-linux-musl.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "c73c4cb1c5c6e74963229394b0ea5d5005ae3dce"
os = "freebsd"

    [[libmseed.download]]
    sha256 = "09bd5ee32c5ea026daf8407858d12baf52dc8b4f607dd94c069e989f3a2326e0"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.x86_64-unknown-freebsd.tar.gz"
[[libmseed]]
arch = "x86_64"
git-tree-sha1 = "288e92fcab42666296f189dc9c8d5342de638b66"
os = "windows"

    [[libmseed.download]]
    sha256 = "23761058e4ba2c799f8a307466fb51647c1fe75e6f5e22e06148d8fd664ab68e"
    url = "https://github.com/JuliaBinaryWrappers/libmseed_jll.jl/releases/download/libmseed-v3.0.17+0/libmseed.v3.0.17.x86_64-w64-mingw32.tar.gz"
