# Autogenerated wrapper script for libmseed_jll for x86_64-w64-mingw32
export libmseed

JLLWrappers.@generate_wrapper_header("libmseed")
JLLWrappers.@declare_library_product(libmseed, "libmseed.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libmseed,
        "bin\\libmseed.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
